services:
  app:
    build: .
    env_file: .env
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./wingz/.:/server
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
