services:
  wingz_backend:
    container_name: wingz_backend
    build: .
    env_file: .env
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./wingz/.:/server
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      postgresdb:
        condition: service_healthy
    links:
      - postgresdb

  postgresdb:
    image: postgis/postgis:15-3.5
    ports:
        - "5432:5432"
    env_file: .env
    volumes:
        - ./postgres:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "wingzdb", "-U", "wingzuser"]
        interval: 5s
        timeout: 5s
        retries: 5
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: local@example.com
  #     PGADMIN_DEFAULT_PASSWORD: abc123!@#
  #   depends_on:
  #     - postgresdb
  #   restart: unless-stopped

volumes:
  database: