# Generated by Django 5.1.5 on 2025-01-17 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="Email")),
                ("first_name", models.CharField(default="first", max_length=30, verbose_name="First name")),
                ("last_name", models.CharField(default="last", max_length=30, verbose_name="Last name")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        error_messages={},
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.BaseValidator(15, message="Enter a valid phone number."),
                            django.core.validators.BaseValidator(15, message="Enter a valid phone number."),
                        ],
                    ),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="Admin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="Superuser")),
                ("created_by", models.CharField(max_length=50, verbose_name="Created by")),
                ("updated_by", models.CharField(max_length=50, verbose_name="Updated by")),
                ("groups", models.ManyToManyField(related_name="user_groups", to="auth.group", verbose_name="Groups")),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="user_permissions", to="auth.permission", verbose_name="Permissions"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email",), name="email", violation_error_message="Email already exist."
                    )
                ],
            },
        ),
    ]
